import { BaseModel } from "./base.model.js";
import type { AnalysisHistory, SummaryJson } from "../types/analysis_history.type.js";

interface CreateHistoryPayload {
  uuid: string;
  user_id: number;
  title: string;
  file_name: string;
}

interface UpdateAfterAnalysisPayload {
  recommendation: string;
  chat_history: SummaryJson;
  detail: string;
}

export class AnalysisHistoryModel extends BaseModel {
  /**
   * Create a new analysis history record after CSV upload.
   * uuid is generated by caller (crypto.randomUUID).
   */
  async create(payload: CreateHistoryPayload): Promise<AnalysisHistory> {
    const query = `
      INSERT INTO analysis_history (uuid, user_id, title, file_name, detail)
      VALUES ($1, $2::bigint, $3, $4, $5)
      RETURNING *
    `;
    const result = await this._db.query(query, [
      payload.uuid,
      payload.user_id,
      payload.title,
      payload.file_name,
      "",   // detail diisi setelah analisis selesai
    ]);
    return result.rows[0] as AnalysisHistory;
  }

  /**
   * Get all non-deleted histories for a user, newest first.
   */
  async getByUserId(userId: number): Promise<AnalysisHistory[]> {
    const query = `
      SELECT *
      FROM analysis_history
      WHERE user_id = $1::bigint
        AND deleted_at IS NULL
      ORDER BY created_at DESC
    `;
    const result = await this._db.query(query, [userId]);
    return result.rows as AnalysisHistory[];
  }

  /**
   * Get a single non-deleted history by uuid.
   */
  async getByUuid(uuid: string): Promise<AnalysisHistory | null> {
    const query = `
      SELECT *
      FROM analysis_history
      WHERE uuid = $1
        AND deleted_at IS NULL
    `;
    const result = await this._db.query(query, [uuid]);
    return (result.rows[0] as AnalysisHistory) ?? null;
  }

  /**
   * Update record after AI analysis completes.
   * Sets recommendation text, chat_history JSONB, and detail summary line.
   */
  async updateAfterAnalysis(
    uuid: string,
    payload: UpdateAfterAnalysisPayload,
  ): Promise<void> {
    const query = `
      UPDATE analysis_history
      SET
        recommendation = $1,
        chat_history   = $2,
        detail         = $3,
        updated_at     = NOW()
      WHERE uuid = $4
    `;
    await this._db.query(query, [
      payload.recommendation,
      JSON.stringify(payload.chat_history),
      payload.detail,
      uuid,
    ]);
  }

  /**
   * Soft-delete a history record.
   */
  async softDelete(uuid: string): Promise<void> {
    await this._db.query(
      `UPDATE analysis_history SET deleted_at = NOW() WHERE uuid = $1`,
      [uuid],
    );
  }
}
